name: Discord Webhook

on:
  workflow_dispatch:
    inputs:
      target_server:
        description: '어느 서버로 보낼지 선택하세요'
        required: true
        type: choice
        options:
          - 리자몽 서버
          - 테스트 서버
          - 보조 서버
          - 발로 랜계no.1
          - 니트로

      custom_message:
        description: '보낼 메시지를 입력하세요'
        required: false
        type: string

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Send Webhook
        env:
          WEBHOOK_URL_1: ${{ secrets.DISCORD_WEBHOOK_URL }}
          WEBHOOK_URL_2: ${{ secrets.DISCORD_WEBHOOK_URL_2 }}
          WEBHOOK_URL_3: ${{ secrets.DISCORD_WEBHOOK_URL_3 }}
          WEBHOOK_URL_4: ${{ secrets.DISCORD_WEBHOOK_URL_4 }}
          WEBHOOK_URL_5: ${{ secrets.DISCORD_WEBHOOK_URL_5 }}
          SELECTED_SERVER: ${{ inputs.target_server }}
          INPUT_MSG: ${{ inputs.custom_message }}

        run: |
          if [ "$SELECTED_SERVER" = "리자몽 서버" ]; then
            WEBHOOK_URL="$WEBHOOK_URL_1"
          elif [ "$SELECTED_SERVER" = "테스트 서버" ]; then
            WEBHOOK_URL="$WEBHOOK_URL_2"
          elif [ "$SELECTED_SERVER" = "보조 서버" ]; then
            WEBHOOK_URL="$WEBHOOK_URL_3"
          elif [ "$SELECTED_SERVER" = "발로 랜계no.1" ]; then
            WEBHOOK_URL="$WEBHOOK_URL_4"
            elif [ "$SELECTED_SERVER" = "니트로" ]; then
            WEBHOOK_URL="$WEBHOOK_URL_5"
          else
            echo "Unknown target server: $SELECTED_SERVER"
            exit 1
          fi
          if [ -z "$WEBHOOK_URL" ]; then
            echo "WEBHOOK_URL is empty"
            exit 1
          fi
          if [ -z "$INPUT_MSG" ]; then
            MSG="테스트 메시지입니다.\nDiscord 웹훅 정상 작동 확인!"
          else
            MSG="$INPUT_MSG"
          fi
          MESSAGE=$(printf '%b' "$MSG")
          response=$(jq -n \
            --arg content "$MESSAGE" \
            '{
              content: $content,
              allowed_mentions: {
                parse: ["everyone"]
              }
            }' \
            | curl -s -o /tmp/resp.txt -w "%{http_code}" \
                -H "Content-Type: application/json" \
                -X POST \
                --data-binary @- \
                "$WEBHOOK_URL")
          if [ "$response" != "204" ]; then
            echo "Discord webhook failed with HTTP $response"
            cat /tmp/resp.txt
            exit 1
          fi
          echo "Discord webhook sent successfully!"
